sudo: required
language: java
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
services:
  - mysql
install:
  - echo "my install"
before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('root') WHERE user='root@localhost';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root')"
script:
  - echo "my script"
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn -B -P upgrade-db -pl server -am install -Dmaven.test.redirectTestOutputToFile=true
deploy:
  provider: script
  script: echo "my deploy"
